/*
 * API de Integração com GCC - Conteúdo
 * Provê funcionalidades para criação, recuperação e atualização de conteúdo no repositório GCC
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cgcc.integracao.conteudo;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Contempla as informações necessárias para reversão da exclusão de conteúdo, através do nome de conteudo
 */
@ApiModel(description = "Contempla as informações necessárias para reversão da exclusão de conteúdo, através do nome de conteudo")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-02T20:33:16.213Z")
public class RequestReverterExclusaoLogicaPorNome {
  @SerializedName("centroCusto")
  private String centroCusto = null;

  @SerializedName("canal")
  private String canal = null;

  @SerializedName("usuario")
  private String usuario = null;

  @SerializedName("senha")
  private String senha = null;

  @SerializedName("objectStore")
  private String objectStore = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("choiceList")
  private String choiceList = null;

  @SerializedName("nomeMetadadoTipoConteudo")
  private String nomeMetadadoTipoConteudo = null;

  @SerializedName("nomeMetadadoStatusConteudo")
  private String nomeMetadadoStatusConteudo = null;

  @SerializedName("classeAssinatura")
  private String classeAssinatura = null;

  public RequestReverterExclusaoLogicaPorNome centroCusto(String centroCusto) {
    this.centroCusto = centroCusto;
    return this;
  }

   /**
   * Centro de custo que esta executando a requisição
   * @return centroCusto
  **/
  @ApiModelProperty(required = true, value = "Centro de custo que esta executando a requisição")
  public String getCentroCusto() {
    return centroCusto;
  }

  public void setCentroCusto(String centroCusto) {
    this.centroCusto = centroCusto;
  }

  public RequestReverterExclusaoLogicaPorNome canal(String canal) {
    this.canal = canal;
    return this;
  }

   /**
   * Canal que está executando a requisição
   * @return canal
  **/
  @ApiModelProperty(required = true, value = "Canal que está executando a requisição")
  public String getCanal() {
    return canal;
  }

  public void setCanal(String canal) {
    this.canal = canal;
  }

  public RequestReverterExclusaoLogicaPorNome usuario(String usuario) {
    this.usuario = usuario;
    return this;
  }

   /**
   * Usuário para autenticação no repositório GCC (o usuário deve estar criptografado no padrão GCC)
   * @return usuario
  **/
  @ApiModelProperty(required = true, value = "Usuário para autenticação no repositório GCC (o usuário deve estar criptografado no padrão GCC)")
  public String getUsuario() {
    return usuario;
  }

  public void setUsuario(String usuario) {
    this.usuario = usuario;
  }

  public RequestReverterExclusaoLogicaPorNome senha(String senha) {
    this.senha = senha;
    return this;
  }

   /**
   * Senha para autenticação no repositório GCC (a senha deve estar criptografada no padrão GCC)
   * @return senha
  **/
  @ApiModelProperty(required = true, value = "Senha para autenticação no repositório GCC (a senha deve estar criptografada no padrão GCC)")
  public String getSenha() {
    return senha;
  }

  public void setSenha(String senha) {
    this.senha = senha;
  }

  public RequestReverterExclusaoLogicaPorNome objectStore(String objectStore) {
    this.objectStore = objectStore;
    return this;
  }

   /**
   * ObjectStore onde será executada a operação no repositório
   * @return objectStore
  **/
  @ApiModelProperty(example = "OS-CAMBIO", required = true, value = "ObjectStore onde será executada a operação no repositório")
  public String getObjectStore() {
    return objectStore;
  }

  public void setObjectStore(String objectStore) {
    this.objectStore = objectStore;
  }

  public RequestReverterExclusaoLogicaPorNome nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome/titulo do conteúdo cuja exclusão será revertida
   * @return nome
  **/
  @ApiModelProperty(example = "F123456987852401382-000-E160.jpg", required = true, value = "Nome/titulo do conteúdo cuja exclusão será revertida")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public RequestReverterExclusaoLogicaPorNome choiceList(String choiceList) {
    this.choiceList = choiceList;
    return this;
  }

   /**
   * Nome da ChoiceList onde será pesquisada a classe do conteúdo a partir do tipo armazenado
   * @return choiceList
  **/
  @ApiModelProperty(example = "lstGccCodigoDocumentoClasse", required = true, value = "Nome da ChoiceList onde será pesquisada a classe do conteúdo a partir do tipo armazenado")
  public String getChoiceList() {
    return choiceList;
  }

  public void setChoiceList(String choiceList) {
    this.choiceList = choiceList;
  }

  public RequestReverterExclusaoLogicaPorNome nomeMetadadoTipoConteudo(String nomeMetadadoTipoConteudo) {
    this.nomeMetadadoTipoConteudo = nomeMetadadoTipoConteudo;
    return this;
  }

   /**
   * Nome do metadado que armazena o tipo do conteúdo (icor)
   * @return nomeMetadadoTipoConteudo
  **/
  @ApiModelProperty(example = "GccCdTipoDocIcor", required = true, value = "Nome do metadado que armazena o tipo do conteúdo (icor)")
  public String getNomeMetadadoTipoConteudo() {
    return nomeMetadadoTipoConteudo;
  }

  public void setNomeMetadadoTipoConteudo(String nomeMetadadoTipoConteudo) {
    this.nomeMetadadoTipoConteudo = nomeMetadadoTipoConteudo;
  }

  public RequestReverterExclusaoLogicaPorNome nomeMetadadoStatusConteudo(String nomeMetadadoStatusConteudo) {
    this.nomeMetadadoStatusConteudo = nomeMetadadoStatusConteudo;
    return this;
  }

   /**
   * Nome do metadado que armazena o status do conteúdo
   * @return nomeMetadadoStatusConteudo
  **/
  @ApiModelProperty(example = "GccCdStatusDocumento", required = true, value = "Nome do metadado que armazena o status do conteúdo")
  public String getNomeMetadadoStatusConteudo() {
    return nomeMetadadoStatusConteudo;
  }

  public void setNomeMetadadoStatusConteudo(String nomeMetadadoStatusConteudo) {
    this.nomeMetadadoStatusConteudo = nomeMetadadoStatusConteudo;
  }

  public RequestReverterExclusaoLogicaPorNome classeAssinatura(String classeAssinatura) {
    this.classeAssinatura = classeAssinatura;
    return this;
  }

   /**
   * Classe para a qual a assinatura do conteúdo deve ser revertida
   * @return classeAssinatura
  **/
  @ApiModelProperty(example = "docGccAssinatura", required = true, value = "Classe para a qual a assinatura do conteúdo deve ser revertida")
  public String getClasseAssinatura() {
    return classeAssinatura;
  }

  public void setClasseAssinatura(String classeAssinatura) {
    this.classeAssinatura = classeAssinatura;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestReverterExclusaoLogicaPorNome requestReverterExclusaoLogicaPorNome = (RequestReverterExclusaoLogicaPorNome) o;
    return Objects.equals(this.centroCusto, requestReverterExclusaoLogicaPorNome.centroCusto) &&
        Objects.equals(this.canal, requestReverterExclusaoLogicaPorNome.canal) &&
        Objects.equals(this.usuario, requestReverterExclusaoLogicaPorNome.usuario) &&
        Objects.equals(this.senha, requestReverterExclusaoLogicaPorNome.senha) &&
        Objects.equals(this.objectStore, requestReverterExclusaoLogicaPorNome.objectStore) &&
        Objects.equals(this.nome, requestReverterExclusaoLogicaPorNome.nome) &&
        Objects.equals(this.choiceList, requestReverterExclusaoLogicaPorNome.choiceList) &&
        Objects.equals(this.nomeMetadadoTipoConteudo, requestReverterExclusaoLogicaPorNome.nomeMetadadoTipoConteudo) &&
        Objects.equals(this.nomeMetadadoStatusConteudo, requestReverterExclusaoLogicaPorNome.nomeMetadadoStatusConteudo) &&
        Objects.equals(this.classeAssinatura, requestReverterExclusaoLogicaPorNome.classeAssinatura);
  }

  @Override
  public int hashCode() {
    return Objects.hash(centroCusto, canal, usuario, senha, objectStore, nome, choiceList, nomeMetadadoTipoConteudo, nomeMetadadoStatusConteudo, classeAssinatura);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestReverterExclusaoLogicaPorNome {\n");
    
    sb.append("    centroCusto: ").append(toIndentedString(centroCusto)).append("\n");
    sb.append("    canal: ").append(toIndentedString(canal)).append("\n");
    sb.append("    usuario: ").append(toIndentedString(usuario)).append("\n");
    sb.append("    senha: ").append(toIndentedString(senha)).append("\n");
    sb.append("    objectStore: ").append(toIndentedString(objectStore)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    choiceList: ").append(toIndentedString(choiceList)).append("\n");
    sb.append("    nomeMetadadoTipoConteudo: ").append(toIndentedString(nomeMetadadoTipoConteudo)).append("\n");
    sb.append("    nomeMetadadoStatusConteudo: ").append(toIndentedString(nomeMetadadoStatusConteudo)).append("\n");
    sb.append("    classeAssinatura: ").append(toIndentedString(classeAssinatura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

