/*
 * API de Integração com GCC - Conteúdo
 * Provê funcionalidades para criação, recuperação e atualização de conteúdo no repositório GCC
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cgcc.integracao.conteudo;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Contempla as informações retornadas como resultado da execução da criação de conteúdo no repositório
 */
@ApiModel(description = "Contempla as informações retornadas como resultado da execução da criação de conteúdo no repositório")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-02T20:33:16.213Z")
public class ResponseCriar {
  @SerializedName("status")
  private Integer status = null;

  @SerializedName("mensagem")
  private String mensagem = null;

  @SerializedName("id")
  private String id = null;

  public ResponseCriar status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Status HTTP
   * @return status
  **/
  @ApiModelProperty(value = "Status HTTP")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ResponseCriar mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de retorno
   * @return mensagem
  **/
  @ApiModelProperty(value = "Mensagem de retorno")
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public ResponseCriar id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID do conteúdo criado no repositório
   * @return id
  **/
  @ApiModelProperty(value = "ID do conteúdo criado no repositório")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCriar responseCriar = (ResponseCriar) o;
    return Objects.equals(this.status, responseCriar.status) &&
        Objects.equals(this.mensagem, responseCriar.mensagem) &&
        Objects.equals(this.id, responseCriar.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, mensagem, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCriar {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

