/*
 * API de Integração com GCC - Conteúdo
 * Provê funcionalidades para criação, recuperação e atualização de conteúdo no repositório GCC
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cgcc.integracao.conteudo;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseObter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-02T20:33:16.213Z")
public class ResponseObter {
  @SerializedName("status")
  private Integer status = null;

  @SerializedName("mensagem")
  private String mensagem = null;

  @SerializedName("arquivos")
  private List<String> arquivos = null;

  public ResponseObter status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Status HTTP
   * @return status
  **/
  @ApiModelProperty(value = "Status HTTP")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ResponseObter mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de retorno
   * @return mensagem
  **/
  @ApiModelProperty(value = "Mensagem de retorno")
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public ResponseObter arquivos(List<String> arquivos) {
    this.arquivos = arquivos;
    return this;
  }

  public ResponseObter addArquivosItem(String arquivosItem) {
    if (this.arquivos == null) {
      this.arquivos = new ArrayList<String>();
    }
    this.arquivos.add(arquivosItem);
    return this;
  }

   /**
   * Lista dos arquivos que compoem o conteúdo, em Base 64
   * @return arquivos
  **/
  @ApiModelProperty(value = "Lista dos arquivos que compoem o conteúdo, em Base 64")
  public List<String> getArquivos() {
    return arquivos;
  }

  public void setArquivos(List<String> arquivos) {
    this.arquivos = arquivos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseObter responseObter = (ResponseObter) o;
    return Objects.equals(this.status, responseObter.status) &&
        Objects.equals(this.mensagem, responseObter.mensagem) &&
        Objects.equals(this.arquivos, responseObter.arquivos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, mensagem, arquivos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseObter {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    arquivos: ").append(toIndentedString(arquivos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

